### ISSUE TITLE
Can not update laravel 11

### ISSUE THREAD

**Issue by erenergul** [outer-web/filament-settings#5]
- outerweb/settings[v1.0.0, ..., v1.0.2] require laravel/framework ^10.0 -> found laravel/framework[v10.0.0, ..., v10.48.7] but it conflicts with your root composer.json require (^11.0).
    
    - outerweb/filament-settings v1.2.0 requires outerweb/settings ^1.0 -> satisfiable by outerweb/settings[v1.0.0, v1.0.1, v1.0.2, v1.0.3].

i install latest version of outweb/settings but still say same things.

**Comment by SimonBroekaert** [comment]
L11 is support with:

- Filament Settings from 1.1.1 and up https://github.com/outer-web/filament-settings/blob/main/CHANGELOG.md
- Settings from 1.0.3 and up https://github.com/outer-web/settings/blob/main/CHANGELOG.md

Can you try with those versions?

**Comment by SimonBroekaert** [comment]
Hi @erenergul , I will close this issue for now. If my previous comment did not supply u with a solution, feel free to open this issue again.
